name: miebach-project

services:
    frontend:
        build:
            context: "./frontend"
            dockerfile: "frontend.Dockerfile"
        container_name: miebach-frontend
        ports:
            - 5173:5173
        environment:
            - NODE_ENV=production
            - TZ=America/Toronto
        restart: unless-stopped
    backend:
        build:
            context: "./backend"
            dockerfile: "backend.Dockerfile"
        container_name: miebach-backend
        ports:
            - 3001:3001
        environment:
            - NODE_ENV=production
            - TZ=America/Toronto
        restart: unless-stopped
